#! /usr/bin/env racket
#lang denxi/launcher

(module+ main
  (require racket/cmdline
           racket/path
           racket/port
           denxi/dig/filesystem)

  (define (write-bytes-to-file! path byte-string)
    (call-with-output-file path
      (λ (to-file)
        (copy-port (open-input-bytes byte-string)
                   to-file))))

  (command-line #:args (user-chf-string private-key-path private-key-password-path . user-paths)
   (for ([user-path (in-list user-paths)])
     (parameterize ([current-chfs (build-builtin-chf-trust (list (string->symbol user-chf-string)))])
       (define chf (get-default-chf))
       (define expanded-user-path (expand-user-path user-path))
       (define digest-file-path (make-digest-file-path expanded-user-path chf))
       (define signature-file-path (make-signature-file-path digest-file-path))
       (define digest (make-digest expanded-user-path))
       (define signature (make-signature digest chf (file->bytes private-key-path) (file->bytes private-key-password-path)))
       (write-bytes-to-file! digest-file-path digest)
       (write-bytes-to-file! signature-file-path signature)))))
